### ISSUE TITLE
Possible memory leak with clones

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#101]
Clones will start a new thread when created, but don't seem to stop it. Thus, creating and deleting clones every frame will cause massive slowdown and eventually an outOfMemory exception.

**Comment by lucentlavender** [comment]
It appears the OutOfMemoryException doesn't happen under all circumstances, but the slowdown does.

**Comment by VictorNorman** [comment]
How do you know the threads are not exiting?  Please attach a test case and/or more explanation.

**Comment by lucentlavender** [comment]
It's more of an assumption. I don't see anything to stop the thread in deleteThisClone(). 
[fire.zip](https://github.com/VictorNorman/ScratchFoot/files/386802/fire.zip) will run very quickly at first, but will very quickly slow down, despite the number of clones remaining fairly constant.

**Comment by lucentlavender** [comment]
This appears to be two different issues, I will close this and open new, more specific issues for those.
