### ISSUE TITLE
Thread resource leak with methods that take Sequence as an argument inside of clones

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#114]
Certain thread never seem to end, even when restarting greenfoot. (You must kill the java instance greenfoot generates in order to release the threads). Test performed with your rock paper scissors simulation

After starting greenfoot, but before hitting the flag
![Before running](https://cloud.githubusercontent.com/assets/19914457/17303719/dad8d740-57ef-11e6-95d8-6800047027c1.PNG)
After running the program for a minute (It seems 1-2 threads show up every time an object changes)
![While Running](https://cloud.githubusercontent.com/assets/19914457/17303744/f824a194-57ef-11e6-867f-33108e2ad72f.PNG)
After running the simulation 4 times, despite hitting reset between every run, the threads continue to pile up.
![rpsafter](https://cloud.githubusercontent.com/assets/19914457/17303863/807d0798-57f0-11e6-905a-7c6c536e2247.PNG)
Even just clicking restart over and over again causes thread to accumulate. 20 or so restarts after re-instancing java: 
![rpsrestart](https://cloud.githubusercontent.com/assets/19914457/17303924/eafb6e2a-57f0-11e6-9e86-5f5442931ba1.PNG)

**Comment by VictorNorman** [comment]
This may have to do with garbage collection.

Threads exit when the run() method completes, which should happen, as I see it.

But, they may not be garbage collected in the JVM, i think.  I'm just speculating.

More research needs to be done, I think.

**Comment by lucentlavender** [comment]
~~I really don't remember much about multithreading in java, but don't you have to call join() or something to close a thread for GC?~~ After a little research, this doesn't seem to be the case.

**Comment by lucentlavender** [comment]
If a "whenIStartAsAClone" method has a 'yield' statement, or any other statement which takes a Sequence as an argument, the thread will not close when the clone is deleted. If there is no yield, the thread will exit once the clone is deleted. Upon further testing it appears this leak only happens if the deleteThisClone call comes before the sequence method.
