### ISSUE TITLE
getAttribute not implemented

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#115]
Should always use the parent object, not any clone.
First argument is always literal
  -Could be any local variable or local data (x coord, size, etc)
Second argument is a strExpr that should evaluate to a sprite name or "_stage_".

**Comment by VictorNorman** [comment]
I don't understand: I have getAttribute implemented.

Search in s2g.py for "def getAttributeOf" -- line 494 in my copy.

**Comment by lucentlavender** [comment]
I see, yours is implemented only in mathExpr, and doesn't work for getting other sprites local variables. I will update that code and add it to strExpr
