### ISSUE TITLE
Is there an issue with changing s2g utf-8?

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#117]
The only way that cloud variables in scratch are differentiated are by having the character '☁' as the first character in their name. In order to check if this is present s2g must be saved in utf-8. I don't know if this will cause any problems.

**Comment by VictorNorman** [comment]
OK, I think I figured this out.

We can handle the encoding without storing s2g.py in utf-8.

I opened a project.json file and read all lines into a list with readlines().

I found that line2 was:

'\t\t\t"name": "? high score",\n'

With this code, I figured out that the little cloud symbol is character 12:

> > > for i, c in enumerate(l[2]):

...     print(i, c)

...

0

1

2

3 "

4 n

5 a

6 m

7 e

8 "

9 :

10

11 "

12 ?

13

14 h

15 i

16 g

17 h

18

19 s

20 c

21 o

22 r

23 e

24 "

25 ,

26

This shows the values for that character:

> > > l[2].encode('utf-8')

b'\t\t\t"name": "\xe2\x98\x81 high score",\n'

> > > for i, c in enumerate(e):

...     print(i, c)

...

0 9

1 9

2 9

3 34

4 110

5 97

6 109

7 101

8 34

9 58

10 32

11 34

12 226

13 152

14 129

15 32

16 104

17 105

18 103

19 104

20 32

21 115

22 99

23 111

24 114

25 101

26 34

27 44

28 10

So, bytes 12, 13, and 14 have hex values 0xe2, 0x98, and 0x81 in them. Byte 15 is a space (value 0x20)

So, we can write code like this to see if a variable is a cloud variable:

> > > if e[12] == 0xe2 and e[13] == 0x98 and e[14] == 0x81 and e[15] == 0x20:

...    print("Yes: it is a cloud variable!")
