### ISSUE TITLE
Implement list variables and supporting functions

### ISSUE THREAD

**Issue by VictorNorman** [VictorNorman/ScratchFoot#118]

**Comment by lucentlavender** [comment]
Lists could be implemented as a typed array/list (int, double, String, etc) as would be typical of java, or they could be implemented as a list of Variables (the class in scratch.java). This would allow them to hold multiple types in the same list (like scratch), and a lot of the logic from variables could be reused. Which do you prefer?

**Comment by VictorNorman** [comment]
I guess the latter would be better.  Would the Variables stuff help with displaying the lists on the screen, as Scratch can do?

**Comment by lucentlavender** [comment]
Yes, potentially.

**Comment by lucentlavender** [comment]
This has been implemented in Scratch.java, but still needs implementing in s2g. It should be implemented similarly to genVariableDefnCode, but looking at the lists rather than variables. I'm not sure how to add it so that it generates correctly with the new class based system.

**Comment by lucentlavender** [comment]
This was closed by 6a0065f82f29893d3cb4df36c34159215da52623 a while ago.
