### ISSUE TITLE
Pen size could probably be implemented with Path

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#120]
Pen size could be done by drawing a [Path](https://docs.oracle.com/javase/7/docs/api/java/awt/geom/Path2D.html) with drawShape() rather than using drawLine().

**Comment by VictorNorman** [comment]
I'd love to see the implementation of this.

**Comment by lucentlavender** [comment]
I'll look into it when I get to it on my ToDo list.
