### ISSUE TITLE
Can we move all "global" variables to Stage instead of World?

### ISSUE THREAD

**Issue by VictorNorman** [VictorNorman/ScratchFoot#125]
If we do this, then maybe we could remove all the ScratchWorld.IntVar stuff...  not sure of all the implications.

**Comment by lucentlavender** [comment]
There are a few differences in the variable code between Scratch and ScratchWorld that would need to be resolved, but this shouldn't be too much of a hassle.

**Comment by lucentlavender** [comment]
Closed by f08e48b23a1057ec1a1b7c08a6b0be8bc4d39dbe
