### ISSUE TITLE
s2g returns "NO SCRIPTS FOUND" when converting program with scripts

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#126]
[test17.sb2.zip](https://github.com/VictorNorman/ScratchFoot/files/406839/test17.sb2.zip)

**Comment by lucentlavender** [comment]
It seems that this is not actually a bug, just some left over debug output, which I have moved to verbose output. Closed by 17c1600c04b299d875c38b06f38abf2153c8530f

**Comment by VictorNorman** [comment]
D'oh!
