### ISSUE TITLE
stopOtherScriptsInThisSprite doesn't seem to work.

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#128]
In https://scratch.mit.edu/projects/117996924/#editor the apple stops moving after a short distance, in GF it doesn't stop.

**Comment by VictorNorman** [comment]
You need to Share your project for me to be able to see it.  Please do so, and then reassign the bug back to me.

**Comment by lucentlavender** [comment]
I believe it's now shared.

**Comment by lucentlavender** [comment]
Closed by 6a0065f82f29893d3cb4df36c34159215da52623
