### ISSUE TITLE
Race condition?  Rock, Paper, Scissors predator-prey sim has a prey becoming unextinct.

### ISSUE THREAD

**Issue by VictorNorman** [VictorNorman/ScratchFoot#130]
I've seen this twice now: 

I convert the Scratch Rock, Paper, Scissors predator-prey simulation to Greenfoot and run it.  I see one "species" go down to zero and the other 2 are battling it out... Then, suddenly a clone of the extinct species shows up again...  

This seems to happen more often when I run the simulation very fast in Greenfoot.  It is probably some very very nasty race condition.  Not sure how we'll debug this...

**Comment by lucentlavender** [comment]
I was having this issue earlier because they were sometimes detecting
collision with the invisible parent object. I thought I fixed it, but I would
check to make sure this isn't the case first.

**Comment by VictorNorman** [comment]
That actually might be it...
