### ISSUE TITLE
Because s2g automatically capitalizes sprite names, methods that take an object name may be incorrect

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#138]
For example, if in scratch I have a sprite named "sprite1", when converted to greenfoot it will be "Sprite1". However, if in scratch I have isTouching [sprite1], greenfoot will convert that to isTouching("sprite1"). This will throw a nullPointerException because the names have different capitalization. This could be solved either by making the Scratch.java methods non case-sensitive, or by doing some magic in s2g to capitalize the string literal.

**Comment by VictorNorman** [comment]
Well, we do have to capitalize the names of Sprites because they are Java classes, and Greenfoot is quite particular about that, and besides, it is good style.

So, I guess we have to make some changes in s2g.py to use the changed/sanitized name.

**Comment by lucentlavender** [comment]
What I meant by making it non case-sensitive was to make the method ignore the case

```
isTouching(String name) {
    actor = getActorByName(name.capitalizeFirstLetter()); 
    // or whatever code would do this
```

This way the user can pass either "spritename" or "Spritename" and (since the class will always start with a capital) get the right object.
