### ISSUE TITLE
Scratch seems to do some amount of approximation when comparing colors

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#141]
For example, a project I downloaded had the color 000008 and 000001 (both nearly black, barely distinguishable from each other) and both are affected by the same "is touching color" block that is set to 000008. I'm not sure if this should be implemented.

**Comment by VictorNorman** [comment]
Wow, that is weird.

I'll post a question about this on the Scratch Forum and see what people say.

**Comment by VictorNorman** [comment]
Wow.  Look at the great response I received on the forum:

https://scratch.mit.edu/discuss/topic/215162/?page=1#post-2170780

**Comment by VictorNorman** [comment]
Jordan,

I hope you ran some pretty good tests on this before submission.  Now that the public knows about this tool, we have to be more careful to keep the repository in a good state at all times.

Thanks.

**Comment by lucentlavender** [comment]
I haven't tested everything. I'm working on a larger set of related changes, if you want you can revert my change so I can finish what I'm doing locally, test everything, then re-commit.

**Comment by VictorNorman** [comment]
Ok.  That's fine.  Just don't let it sit too long.  People are visiting the site every day now, from what I've seen.

**Comment by lucentlavender** [comment]
Alright, I've tested it and haven't found any new issues.
