### ISSUE TITLE
Implement a quad-tree to improve collision detection

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#146]

**Comment by lucentlavender** [comment]
So I have 2 options of how to use the quad tree. The blue outlines represent tree divisions, the black means that that block has only transparent pixels, red means it has only opaque pixels, and green means that it is partially filled and must be checked again later.

This is how it looks using a fixed depth tree. This takes about 22-23 milliseconds to build if the sprite is approximately the size of the whole stage.
![fixeddepth](https://user-images.githubusercontent.com/19914457/27349208-8583ad00-55c4-11e7-8514-70b7c2811c14.gif)
Note that this would require all the green squares to to be checked pixel-by-pixel during collison masking

The other option is unbounded depth. This version goes all the way down to single pixels. This takes 23-24 ms to build (about 2 ms longer), but would mean collsion detection could be done entirely with the tree, the image would never need to be checked.
![infinitedepth](https://user-images.githubusercontent.com/19914457/27348710-fdb4c720-55c2-11e7-905d-ec86dd2c6983.gif)
I don't know which would be preferred.

**Comment by VictorNorman** [comment]
22 milliseconds vs 24 milliseconds is really a meaningless difference, IMO.  I assume the unbounded depth method would mean the code is simpler?  If that is the case, definitely go that route.


And, wow, those graphics are really cool!

________________________________

**Comment by lucentlavender** [comment]
Through some optimization, I've managed to get the ~20ms build time down to ~1ms. This means it can generate the entire tree and detect a worst case collision in significantly less than the time it would take the old iterative collision detection system's average case.
