### ISSUE TITLE
Sequences do not exit when the greenfoot scenario resets

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#150]
This is at least part of the cause of the thread leak issue.

What I believe is happening here:
Sprite1's constructor is called, which calls whenFlagClickedCb1()
whenFlagClickedCb1() creates a sequence and starts it.
The sequence's run() method begins, and calls sequenceLock.wait(), suspending execution
As expected, when start is clicked, the sequence is notified, executes once, then returns to wait()
However, if reset is clicked, the main thread is suspended and the scratch class is reconstructed.
Because of this, the reference to the FlagClicked sequence is lost.
But the sequence is still suspended in its run() call, so it is still considered running, and thus is not eligible for garbage collection.
Thus, the orphaned thread is stuck; it will never receive a notify() or interrupt() allowing it to complete.

The same thing can happen with the other types of sequence.

Potential paths to solution:
- Store a static reference to all active sequences, and in the constructor iterate through it to end all the threads.
- Have the threads periodically wake up to check if they need to exit.
- I've also posted on the greenfoot forums to see if anyone has a better solution

**Comment by VictorNorman** [comment]
There may be some functions in the Java Thread API that can help us.


Each thread has a STATE -- maybe our threads' states are changing and we could detect that and have the thread exit?  Maybe we have to use a ThreadGroup?  There is activeCount() -- might help to detect orphaned threads?


Etc: see http://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html

Thread (Java Platform SE 7 ) - Oracle Help Center<http://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html>
docs.oracle.com
A thread is a thread of execution in a program. The Java Virtual Machine allows an application to have multiple threads of execution running concurrently.



________________________________

**Comment by lucentlavender** [comment]
I've managed to get half of the threads to close properly, but there are still a few leaking, and I'm not sure where they're coming from. They don't seem to be sequences, so they must be coming from somewhere else.

**Comment by lucentlavender** [comment]
I've managed to fix the main problem, but one of the leaks is due to how I implemented sound clips. I'll need to rework that in order to actually solve this problem.
