### ISSUE TITLE
Use ttk to improve look and feel of GUI

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#163]
ttk widgets are not the same size as their respective tk widgets, nor do they have the same configuration options, so this is a bit bigger of a task than it initially seems

**Comment by lucentlavender** [comment]
It appears that ttk has no good way to change the color of either the box or the text, so switching entirely to ttk is not a good solution either.

**Comment by VictorNorman** [comment]
Seems like a regular tkinter OptionMenu will produce the drop-down list I'm thinking of.

________________________________
