### ISSUE TITLE
ifOnEdgeBounce() allows actor to overlap screen edge

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#19]
In scratch the sprite's direction is reversed if any part of the sprite's bounding box overlaps the screen edge. The greenfoot version does not bounce until the center of the sprite overlaps the edge. Test name:Beetle_penupdown.java

**Comment by VictorNorman** [comment]
Hmmm.... I'll have to think if it is easy to fix this or worth fixing it...  Good find!

**Comment by VictorNorman** [comment]
Please identify here the name of the test that demonstrates this.

**Comment by lucentlavender** [comment]
Still need to fix for isTouchingEdge
