### ISSUE TITLE
isTouchingMouse returns null if the mouse is not moving, even if it is on a sprite

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#31]
Test Name: Beetle_touching.java

**Comment by lucentlavender** [comment]
This appears to be because mouseInfo.getActor() returns null if the mouse is not moving.

**Comment by VictorNorman** [comment]
isTouchingMouse() returns a boolean.  Do you mean that it returns false if the mouse is not moving?

**Comment by lucentlavender** [comment]
This was an issue with the Greenfoot MouseInfo class being null if the mouse was not moving. I'm pretty sure I fixed this issue when I implemented the new isTouchingMouse method, but forgot to close this.

**Comment by lucentlavender** [comment]
isTouchingMouse has been improved to check the exact pixel, as opposed to the previous greenfoot version that would be true even if the pixel were transparent.
