### ISSUE TITLE
createCloneOfMyself causes crash

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#41]
Caused by: java.lang.NullPointerException
    at greenfoot.World.addObject(World.java:396)
    at Scratch.createCloneOf(Scratch.java:956)
    at Scratch.createCloneOfMyself(Scratch.java:935)
    at Beetle.whenFlagClickedCb0(Beetle.java:28)

**Comment by VictorNorman** [comment]
You should put more info in here on how to reproduce this.  What code causes this?  Do you have it stored somewhere?

**Comment by lucentlavender** [comment]
I don't have the code saved, but whenever I added "createCloneOfMyself();" anywhere, it would cause that crash every time. Maybe it has something to do with linux?

**Comment by lucentlavender** [comment]
For me, the method callConstructor returns null seemingly no matter what. Is it possibly something to do with the fact that I'm on linux?

**Comment by VictorNorman** [comment]
I have no idea...

**Comment by lucentlavender** [comment]
Seems to have been fixed by the copy constructor change
