### ISSUE TITLE
*World.java not added

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#43]
jld73@syslab20:~/ScratchFoot$ python3 s2g.py /home/jld73/test6.sb2 /home/jld73/test6
Unpacking Scratch download file.
Copying image files to /home/jld73/test6/images
Executing shell command: convert -background None /home/jld73/test6/scratch_code/3.svg /home/jld73/test6/images/3.png
Command to convert svg file to png succeeded
Executing shell command: convert -background None /home/jld73/test6/scratch_code/2.svg /home/jld73/test6/images/2.png
Command to convert svg file to png succeeded
Executing shell command: convert -background None /home/jld73/test6/scratch_code/1.svg /home/jld73/test6/images/1.png
Command to convert svg file to png succeeded

----------- Sprite: Bananas ----------------
Writing code to /home/jld73/test6/Bananas.java.

----------- Sprite: Sprite1 ----------------
Writing code to /home/jld73/test6/Sprite1.java.
Writing code to /home/jld73/test6/Stage.java.
Writing code to /home/jld73/test6World.java.
jld73@syslab20:~/ScratchFoot$ python3 s2g.py /home/jld73/test6.sb2 /home/jld73/test6^C
jld73@syslab20:~/ScratchFoot$

**Comment by VictorNorman** [comment]
https://github.com/VictorNorman/ScratchFoot/commit/977f4b12c30590aa30d0773551f9490de7b0cc4a
