### ISSUE TITLE
Using a monospaced font may make variable display easier

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#48]
The spacing issues on variables seem to caused by the variable width of letters in the display name. Using a monospaced font would make it much easier to determine the length of a string.

**Comment by VictorNorman** [comment]
If you would like to try to fix this, I'd be most obliged.

**Comment by VictorNorman** [comment]
Why is this closed? Did you submit something?

**Comment by lucentlavender** [comment]
Yes, before I left two weeks ago I submitted 900edb76a74c1ff91a4a663b5444cc9dcf713bfc which solved this. At the time you hadn't merged it so I didn't close this issue.

**Comment by VictorNorman** [comment]
But that code doesn't add using a fixed-width font...

**Comment by lucentlavender** [comment]
The second line changed:

```
image.setFont(new java.awt.Font("Courier", java.awt.Font.PLAIN, 12));
```

**Comment by VictorNorman** [comment]
Ah.  You need to make a similar change in Scratch.java.
