### ISSUE TITLE
Issues with blank input fields

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#49]
Say with a blank string should be ignored. Currently creates an empty speech bubble.

GlideTo not implemented
PointTowards not implemented

if/else block with no condition crashes s2g.py
waituntil with no condition crashes s2g.py
repeatuntil with no condition crashes s2g.py

**Comment by VictorNorman** [comment]
glideTo and pointTowards fixed by submissions f5c3d4c

**Comment by VictorNorman** [comment]
Fixed by 10d9904
