### ISSUE TITLE
Sprites are too small

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#53]
This may be a version issue, but since you changed the sprite conversion size my sprites are 1/2 of the size they should be. For example, a sprite that occupies the whole scratch window will require a 2x2 of that sprite to fill the greenfoot window.

**Comment by VictorNorman** [comment]
I just noticed the same thing.  I'm trying to figure out why I did this.  I know that when I did it, I compared the size of the sprite in a Greenfoot window to the one in the Scratch window and they were exactly the same size (after cutting the size 50% in each dimension).  Now, on my Mac I notice they appear to be too small...

**Comment by VictorNorman** [comment]
Try converting my "Beetle drawing (MACUL lesson 2)" Scratch project.  Are the sprites the same size after converting?  If so, why are they the same in this scenario and not in other scenarios?

**Comment by VictorNorman** [comment]
Take a look at project.json for this Beetle one and for another one or two projects.  Maybe I've shrunk the image in the Beetle project, but not in others.  If so, that scaling should be noted somewhere in that json file.  If you can identify where, then we can use that number in s2g.py to do the conversion correctly for all Scratch images.

**Comment by lucentlavender** [comment]
Yes, in that scratch project the beetle has been scaled to 50%, which can
be found in the project.json ' "scale": ' tag.

**Comment by VictorNorman** [comment]
You think you are up to making that change to s2g.py?

**Comment by lucentlavender** [comment]
I'll try, but I haven't really worked with s2g.
