### ISSUE TITLE
s2g doesn't work for me on windows 10

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#54]
It copies the images over then says: 'identify' is not recognized as an internal or external command...

**Comment by VictorNorman** [comment]
Try uninstalling it and installing again.  This time, while installing, there is a dialog box with a bunch of checkboxes on it.  one of them is something like "install legacy command-line tools".  It is unselected by default.  You need to select before continuing.

I have that info here in the README.md, although it probably isn't completely accurate.

https://github.com/VictorNorman/ScratchFoot#how-to-convert-a-scratch-program-to-a-scratchfoot-ie-greenfoot-scenario

**Comment by lucentlavender** [comment]
What am I reinstalling? Python? Greenfoot?

**Comment by VictorNorman** [comment]
ImageMagick

**Comment by lucentlavender** [comment]
No, it still has the same error.

**Comment by VictorNorman** [comment]
OK.  I'll have to check it out.  Tx.

**Comment by VictorNorman** [comment]
On myWindows10 machine, "identify" is found in

C:\Program Files\ImageMagick-7.0.2-Q16\identify.exe

"convert" is found in the same place.

You can use "where convert" from the CMD prompt to find the location of "convert".

Let me know if you see one or both on your Win 10 machine.

(Are you on Win 10?)

**Comment by lucentlavender** [comment]
Yes, I can see both convert.exe and identify.exe in that directory.

**Comment by VictorNorman** [comment]
So, the call from python to "convert" worked, but the call to "identify" did not?  That is weird...

**Comment by lucentlavender** [comment]
Ah, never mind, after a restart it's working fine. The path variable
probably didn't update properly.
