### ISSUE TITLE
No clone limit

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#56]
In scratch there is a limit to the number of clones that can be on screen at once, preventing the program from fork-bombing itself with clones. In greenfoot the clones will keep spawning until it stops responding. This is not necessarily something that needs to be changed, as it would terrible programming practice to rely on a limit such as that.

**Comment by VictorNorman** [comment]
We are not going to implement this limitation.  This is one of the reasons to switch to Greenfoot from Scratch.
