### ISSUE TITLE
If a sprite is hidden when converted, no image is linked

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#64]
If a sprite was hidden, then converted, it will not have any sprite attatched in greenfoot, and will therefore show up as the placeholder sprite when show is called.

**Comment by VictorNorman** [comment]
"converted"?   What do you mean by that?

**Comment by lucentlavender** [comment]
Converted from scratch to GF

**Comment by VictorNorman** [comment]
I assigned this to you.  Please look at the project.json (and s2g.py) and try to figure out why this doesn't happen.

**Comment by lucentlavender** [comment]
I can't seem to replicate this any more. It's possible that some other change fixed this too.
