### ISSUE TITLE
A "When Stage Clicked" block on the stage will not work because the stage has no image

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#70]
Since the stage has no image, no matter where you click it does not count as clicking on the stage.

**Comment by VictorNorman** [comment]
Wow!  Big mistake in s2g.py for this.  When you have "whenStageClicked" in the Stage script in Scratch, the json is "whenClicked:".  s2g.py just generates this as "whenSpriteClicked".  D'oh!
