### ISSUE TITLE
Make functions that take Double values instead of int

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#72]
This would reduce the need for casting in the generated file, and make variables work even when decimals.

**Comment by lucentlavender** [comment]
Closed by 8f22221b5de1806e30ea8b45c0eafac964ba81a9 1690867b55c9aa2a3586df6ea990a706bad220e2

**Comment by VictorNorman** [comment]
Did you miss line 1979 in setGhostEffectTo()?

**Comment by VictorNorman** [comment]
Does this mean we could change s2g.py to not generate calls with casts in them?  I.e., never generate code with (int) casts?

**Comment by lucentlavender** [comment]
Yes, any casts used in the affected methods can have those casts removed.
