### ISSUE TITLE
Greenfoot hangs trying to run the conversion of my Rock Paper Scissors Scratch project

### ISSUE THREAD

**Issue by VictorNorman** [VictorNorman/ScratchFoot#93]
https://scratch.mit.edu/projects/30439856/

**Comment by VictorNorman** [comment]
I think we may have to reduce the simulation down to basics and slowly build it back up again until something hangs.  Then we'll know better where the problem lies.

**Comment by lucentlavender** [comment]
This works fine for me. The only issue I am having with it is that sometimes a sprites seem to randomly appear out of nowhere when collisions happen.

**Comment by VictorNorman** [comment]
Good to know.  Might be a Greenfoot on Mac OS thing...

**Comment by lucentlavender** [comment]
Closing this for now, as it doesn't seem to be a problem we can fix.
