### ISSUE TITLE
getWorld() revision

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#94]
Currently, the code required to get the world is ((___World)getWorld()), so the code for a simple friction movement is:

```
public void whenFlagClickedCb0(Sequence s)
{
    while (true)        // forever loop
    {
        changeXBy(((LrWorld)getWorld()).speed.get());
        ((LrWorld)getWorld()).speed.set((((LrWorld)getWorld()).speed.get() / 1.3));
        if (isKeyPressed("left"))            {
            ((LrWorld)getWorld()).speed.set(((LrWorld)getWorld()).speed.get() + -2);
        }
        if (isKeyPressed("right"))            {
            ((LrWorld)getWorld()).speed.set(((LrWorld)getWorld()).speed.get() + 2);
        }
        yield(s);   // allow other sequences to run
    }
}
```

By adding the following after the constructor: 

```
private LrWorld world;
public void addedToWorld(World w)
{
    world = (LrWorld)w;
}
```

it can be reduced to:

```
public void whenFlagClickedCb0(Sequence s)
{
    while (true)        // forever loop
    {
        changeXBy(world.speed.get());
        world.speed.set(world.speed.get() / 1.3);
        if (isKeyPressed("left"))            {
            world.speed.set(world.speed.get() + -2);
        }
        if (isKeyPressed("right"))            {
            world.speed.set(world.speed.get() + 2);
        }
        yield(s);   // allow other sequences to run
    }
}
```

Note that the "addedToWorld" method is currently only generated if a sprite has local variables, this change would require it to generate if the sprite does anything with variables. This may actually be a good thing to include; since the constructor has many limitations in greenfoot, having an accessible initialization method after the sprite has been added may be helpful to users.

**Comment by VictorNorman** [comment]
That is really nice.  "Make it so". https://youtu.be/-ZxHAZChcYU

[https://i.ytimg.com/vi/-ZxHAZChcYU/hqdefault.jpg]https://youtu.be/-ZxHAZChcYU

Picard - Make It Sohttps://youtu.be/-ZxHAZChcYU
youtu.be
